import { AudioCategory, AudioTrack } from '../types/index';

export const AUDIO_CATALOG: AudioTrack[] = [
  // 1. Preparação Matinal & Blindagem Mental
  {
    id: 'track-pre-1',
    title: 'O STOP Não é o Problema (IA)',
    subtitle: 'Reprogramação de Identidade Vencedora',
    author: 'Trading Mindset',
    category: 'pre_market',
    durationSeconds: 184,
    formattedDuration: '03:04',
    sourceUri: 'O.STOP.nao.e.o.problema.IA.mp3',
    description: 'Compreenda a natureza do stop loss como ferramenta de proteção patrimonial, e não como falha pessoal.',
  },
  {
    id: 'track-pre-2',
    title: 'O STOP Não é o Problema (Original)',
    subtitle: 'Blindagem Emocional Pré-Abertura',
    author: 'Trading Mindset',
    category: 'pre_market',
    durationSeconds: 190,
    formattedDuration: '03:10',
    sourceUri: 'O.Stop.nao.e.o.problema.EU.mp3',
    description: 'Versão em voz humana da afirmação de proteção e desarmamento de expectativas do stop.',
  },
  {
    id: 'track-pre-3',
    title: 'Auto-Hipnose Para Traders',
    subtitle: 'Blindagem e Alta Performance',
    author: 'Guilherme Cardoso',
    category: 'pre_market',
    durationSeconds: 840,
    formattedDuration: '14:00',
    sourceUri: 'AH-Para.Traders.mp3',
    description: 'Reprogramação subconsciente focada exclusivamente na disciplina e tranquilidade operacional.',
  },

  // 2. Frequências Foco & Binaural Beats (Geradas nativamente pelo sintetizador do app)
  {
    id: 'binaural-alpha-10hz',
    title: 'Ondas Alfa (10 Hz) — Flow State Sniper',
    subtitle: 'Foco Profundo e Calma Operacional',
    author: 'Frequência Binaural Pura',
    category: 'binaural_focus',
    durationSeconds: 1800,
    formattedDuration: '30:00',
    sourceUri: 'binaural:alpha:10',
    isBinauralGen: true,
    binauralFreq: 10,
    description: 'Frequência alfa de 10Hz para induzir o estado de fluxo mental (flow), desacelerando a mente sem causar sonolência.',
  },
  {
    id: 'binaural-theta-6hz',
    title: 'Ondas Teta (6 Hz) — Redução de Ansiedade',
    subtitle: 'Estabilidade Emocional no Pregão',
    author: 'Frequência Binaural Pura',
    category: 'binaural_focus',
    durationSeconds: 1800,
    formattedDuration: '30:00',
    sourceUri: 'binaural:theta:6',
    isBinauralGen: true,
    binauralFreq: 6,
    description: 'Frequência teta de 6Hz ideal para momentos de alta tensão no mercado e volatilidade extrema.',
  },
  {
    id: 'binaural-gamma-40hz',
    title: 'Ondas Gama (40 Hz) — Hiperfoco e Precisão',
    subtitle: 'Processamento Visual e Decisão Rápida',
    author: 'Frequência Binaural Pura',
    category: 'binaural_focus',
    durationSeconds: 1800,
    formattedDuration: '30:00',
    sourceUri: 'binaural:gamma:40',
    isBinauralGen: true,
    binauralFreq: 40,
    description: 'Estimulação de ondas gama para máxima atenção aos padrões de candles e microestrutura do book.',
  },

  // 3. Recuperação Pós-Loss & Anti-Tilt
  {
    id: 'track-loss-1',
    title: 'Você Decide Quando Quebrar',
    subtitle: 'Neurociência para Travar o Cérebro no Loss',
    author: 'Thamara & Neurociência',
    category: 'post_loss',
    durationSeconds: 520,
    formattedDuration: '08:40',
    sourceUri: 'Thamara.-.Voce.decide.quando.QUEBRAR.-.NEUROCIENCIA.para.travar.o.seu.CEREBRO.no.Loss.mp3',
    description: 'Entenda os mecanismos químicos do cérebro no momento da dor da perda e como abortar a espiral do tilt.',
  },
  {
    id: 'track-loss-2',
    title: 'Dica Infalível para Melhorar Resultados',
    subtitle: 'Controle Comportamental Imediato',
    author: 'Rodney Dias',
    category: 'post_loss',
    durationSeconds: 425,
    formattedDuration: '07:05',
    sourceUri: 'Rodney.Dias.-.Siga.esta.DICA.INFALIVEL.e.seus.Resultados.vao.melhorar.mp3',
    description: 'O ajuste fino entre técnica e disciplina que transforma consistência em realidade.',
  },
  {
    id: 'track-loss-3',
    title: 'Gerenciando Emoções Negativas Imediatas',
    subtitle: 'Desarmar o Tilt no Momento Crítico',
    author: 'Guilherme Cardoso',
    category: 'post_loss',
    durationSeconds: 600,
    formattedDuration: '10:00',
    sourceUri: 'AH-Gerenciando.Emocoes.Negativas.Imediatas.mp3',
    description: 'Intervenção rápida para bloquear raiva, frustração ou desespero antes de clicar compulsivamente.',
  },

  // 4. Descompressão Pós-Mercado & Sono Reparador
  {
    id: 'track-decomp-1',
    title: 'Meditação Guiada para Traders',
    subtitle: 'Descompressão e Equilíbrio Mental',
    author: 'Luana Schneider',
    category: 'decompression',
    durationSeconds: 585,
    formattedDuration: '09:45',
    sourceUri: 'Meditacao.Guiada.para.Traders.Luana.Schneider.mp3',
    description: 'Meditação focada em desacelerar os batimentos cardíacos e liberar a tensão muscular acumulada no pregão.',
  },
  {
    id: 'track-decomp-2',
    title: 'Meditação Profunda para Traders',
    subtitle: 'Equilíbrio e Clareza Mental',
    author: 'Guilherme Cardoso',
    category: 'decompression',
    durationSeconds: 1074,
    formattedDuration: '17:54',
    sourceUri: 'Meditacao.Para.Traders.Guilherme.Cardoso.mp3',
    description: 'Sessão completa de visualização mental e recondicionamento subconsciente para consistência.',
  },
  {
    id: 'track-decomp-3',
    title: 'Dormir Melhor e Sono Reparador',
    subtitle: 'Higiene do Sono e Desconexão do Mercado',
    author: 'Guilherme Cardoso',
    category: 'decompression',
    durationSeconds: 900,
    formattedDuration: '15:00',
    sourceUri: 'AH-para.dormir.melhor_guilherme.cardoso.mp3',
    description: 'Feche as cotações mentalmente e prepare um sono profundo e reparador para o próximo pregão.',
  },

  // 5. Audiolivro Trading in the Zone (Mark Douglas)
  {
    id: 'track-tiz-1',
    title: '01. O Caminho para o Sucesso',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 968,
    formattedDuration: '16:08',
    sourceUri: '01.O.Caminho.para.o.Sucesso.mp3',
    description: 'A análise fundamentalista, técnica e a evolução para a análise mental no mercado.',
  },
  {
    id: 'track-tiz-2',
    title: '02. O Fascínio e os Perigos do Trading',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1017,
    formattedDuration: '16:57',
    sourceUri: '02.O.fascinio.e.os.perigos.do.trading.mp3',
    description: 'A atração pela liberdade e a necessidade de criar regras internas estritas.',
  },
  {
    id: 'track-tiz-3',
    title: '03. Assumir Responsabilidade',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1935,
    formattedDuration: '32:15',
    sourceUri: '03.Assumir.responsabilidade.mp3',
    description: 'Moldar seu ambiente mental e assumir a responsabilidade total de cada clique.',
  },
  {
    id: 'track-tiz-4',
    title: '04. Consistência: Um Estado Mental',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 895,
    formattedDuration: '14:55',
    sourceUri: '04.Consistencia.-.um.estado.mental.mp3',
    description: 'Entendendo o risco e o alinhamento de crenças para não hesitar.',
  },
  {
    id: 'track-tiz-5',
    title: '05. A Dinâmica da Percepção',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1570,
    formattedDuration: '26:10',
    sourceUri: '05.A.dinamica.da.percepcao.mp3',
    description: 'Depurando seu software mental e a relação entre medo e distorção da realidade.',
  },
  {
    id: 'track-tiz-6',
    title: '06. A Perspectiva do Mercado',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 2000,
    formattedDuration: '33:20',
    sourceUri: '06.A.perspectiva.do.mercado.mp3',
    description: 'O princípio da incerteza e a característica mais fundamental do mercado.',
  },
  {
    id: 'track-tiz-7',
    title: '07. A Essência do Trader',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 3683,
    formattedDuration: '1:01:23',
    sourceUri: '07.A.essencia.do.trader.mp3',
    description: 'Pensar em termos de probabilidades e o modelo dos cassinos.',
  },
  {
    id: 'track-tiz-8',
    title: '08. Trabalhar com Suas Convicções',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1550,
    formattedDuration: '25:50',
    sourceUri: '08.Trabalhar.com.suas.conviccoes.mp3',
    description: 'Definir o problema e gerenciar crenças conflitantes.',
  },
  {
    id: 'track-tiz-9',
    title: '09. A Natureza das Convicções',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1820,
    formattedDuration: '30:20',
    sourceUri: '09.A.natureza.das.conviccoes.mp3',
    description: 'As origens de uma convicção e como ela impacta nossa vida.',
  },
  {
    id: 'track-tiz-10',
    title: '10. O Impacto das Convicções no Trading',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 2925,
    formattedDuration: '48:45',
    sourceUri: '10.O.impacto.das.conviccoes.mp3',
    description: 'A autoavaliação primária e a eliminação do medo de errar.',
  },
  {
    id: 'track-tiz-11',
    title: '11. Pensar Como um Trader',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 2550,
    formattedDuration: '42:30',
    sourceUri: '11.Pensar.como.um.trader.mp3',
    description: 'O estágio mecânico, a regra do stop loss e a aceitação do risco.',
  },
  {
    id: 'track-tiz-12',
    title: '12. Aprenda com os Cassinos',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1840,
    formattedDuration: '30:40',
    sourceUri: '12.Aprenda.com.os.cassinos.mp3',
    description: 'Como uma vantagem matemática de 55% gera consistência milionária a longo prazo.',
  },

  // 6. Sessões de Auto-Hipnose & Reprogramação
  {
    id: 'track-ah-0',
    title: '0. Instalação do Gatilho de Auto-Hipnose',
    subtitle: 'Fundamentos e Condicionamento',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 1200,
    formattedDuration: '20:00',
    sourceUri: '0.Instalacao.do.Gatilho.de.Auto-Hipnose.mp3',
    description: 'Sessão fundamental para instalar os âncoras e gatilhos de transe consciente para uso diário.',
  },
  {
    id: 'track-ah-traders',
    title: 'Auto-Hipnose Para Traders',
    subtitle: 'Blindagem e Alta Performance',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 840,
    formattedDuration: '14:00',
    sourceUri: 'AH-Para.Traders.mp3',
    description: 'Reprogramação subconsciente focada exclusivamente na disciplina e tranquilidade operacional.',
  },
  {
    id: 'track-ah-disciplina',
    title: 'Fortalecer a Disciplina',
    subtitle: 'Execução Mecânica do Plano',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 780,
    formattedDuration: '13:00',
    sourceUri: 'AH-para.fortalecer.a.disciplina.mp3',
    description: 'Elimine a autossabotagem e fortaleça o respeito irrestrito ao seu plano de trade.',
  },
  {
    id: 'track-ah-ansiedade',
    title: 'Dominar a Ansiedade',
    subtitle: 'Calma e Presença no Pregão',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 720,
    formattedDuration: '12:00',
    sourceUri: 'AH-para.dominar.a.ansiedade.mp3',
    description: 'Desarme a ansiedade de antecipar entradas ou sair cedo demais das operações vencedoras.',
  },
  {
    id: 'track-ah-medo',
    title: 'Dominar o Medo de Operar',
    subtitle: 'Confiança e Aceitação do Risco',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 750,
    formattedDuration: '12:30',
    sourceUri: 'AH-para.dominar.o.medo.mp3',
    description: 'Supere o medo de clicar após uma sequência de stops e restabeleça a frieza técnica.',
  },
  {
    id: 'track-ah-concentracao',
    title: 'Melhorar a Concentração',
    subtitle: 'Foco Laser nos Gráficos',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 690,
    formattedDuration: '11:30',
    sourceUri: 'AH-para.melhorar.a.concentracao_guilherme.cardoso.mp3',
    description: 'Aumente o estado de alerta e a velocidade de leitura do mercado sem sobrecarga mental.',
  },
  {
    id: 'track-ah-identidade',
    title: 'Fortalecer a Sua Identidade Vencedora',
    subtitle: 'Autoimagem e Merecimento',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 810,
    formattedDuration: '13:30',
    sourceUri: 'AH-para.fortalecer.a.sua.identidade_guilherme.cardoso.mp3',
    description: 'Alinhe seu subconsciente com a certeza e merecimento da abundância e dos ganhos consistentes.',
  },
  {
    id: 'track-ah-dormir-2',
    title: 'Dormir Melhor e Relaxar a Mente',
    subtitle: 'Desconexão Total',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 900,
    formattedDuration: '15:00',
    sourceUri: 'AH-para.dormir.melhor_guilherme.cardoso.mp3',
    description: 'Indução suave para um sono profundo que restaura sua clareza cognitiva para o dia seguinte.',
  },
  {
    id: 'track-ah-eficiente',
    title: 'Ser Mais Eficiente e Produtivo',
    subtitle: 'Eliminando a Procrastinação',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 660,
    formattedDuration: '11:00',
    sourceUri: 'AH-para.ser.mais.eficiente.mp3',
    description: 'Condicionamento mental para otimizar suas rotinas diárias e estudos pós-mercado.',
  },
  {
    id: 'track-ah-emocoes-2',
    title: 'Gerenciando Emoções Negativas',
    subtitle: 'Autocontrole Emocional',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 600,
    formattedDuration: '10:00',
    sourceUri: 'AH-Gerenciando.Emocoes.Negativas.Imediatas.mp3',
    description: 'Intervenção rápida para bloquear raiva, frustração ou desespero antes de clicar compulsivamente.',
  },
  {
    id: 'track-ah-prosperidade',
    title: 'Ativando a Prosperidade e Abundância',
    subtitle: 'Eliminando Crenças Limitantes de Dinheiro',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 840,
    formattedDuration: '14:00',
    sourceUri: 'AH-Ativando.a.Prosperidade.e.Abundancia.mp3',
    description: 'Reprograme medos inconscientes de ganhar dinheiro ou sabotar contas lucrativas.',
  },
  {
    id: 'track-ah-sucesso',
    title: 'Criando o Sucesso no Futuro',
    subtitle: 'Visualização Quântica de Metas',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 780,
    formattedDuration: '13:00',
    sourceUri: 'AH-criando.o.sucesso.mp3',
    description: 'Visualize suas metas atingidas com riqueza de detalhes sensoriais e emocionais.',
  },
  {
    id: 'track-ah-perdoando-si',
    title: 'Perdoando a Si Mesmo',
    subtitle: 'Limpando Erros do Passado',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 750,
    formattedDuration: '12:30',
    sourceUri: 'AH-Perdoando.a.Si.Mesmo.mp3',
    description: 'Liberte a culpa de dias ruins de loss e encare cada pregão como uma folha em branco.',
  },
  {
    id: 'track-ah-perdao',
    title: 'Liberando o Perdão',
    subtitle: 'Paz Mental e Leveza',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 720,
    formattedDuration: '12:00',
    sourceUri: 'AH-Liberando.o.Perdao.mp3',
    description: 'Dissolva ressentimentos que consomem sua energia vital e prejudicam suas decisões.',
  },
  {
    id: 'track-ah-criatividade',
    title: 'Liberando Sua Criatividade',
    subtitle: 'Soluções e Novas Perspectivas',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 650,
    formattedDuration: '10:50',
    sourceUri: 'AH-liberando.sua.criatividade.mp3',
    description: 'Desbloqueie novas ideias para aperfeiçoar seu operacional e gerenciamento de risco.',
  },
  {
    id: 'track-ah-dor',
    title: 'Controlar a Dor e Tensão Corporal',
    subtitle: 'Relaxamento Somático Muscular',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 700,
    formattedDuration: '11:40',
    sourceUri: 'AH-para.Controlar.a.Dor.mp3',
    description: 'Alívio para dores nas costas, ombros e cabeça causadas por longas horas diante das telas.',
  },
  {
    id: 'track-ah-memoria',
    title: 'Reforço da Memória e Fixação',
    subtitle: 'Retenção de Padrões Gráficos',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 600,
    formattedDuration: '10:00',
    sourceUri: 'AH-para.Reforco.da.Memoria.mp3',
    description: 'Fixe no subconsciente os padrões de candles, gatilhos de entrada e contextos de mercado.',
  },
  {
    id: 'track-ah-despertando',
    title: 'Despertando na Hora Certa',
    subtitle: 'Disposição Matinal Automática',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 540,
    formattedDuration: '09:00',
    sourceUri: 'AH-Despertando.na.Hora.Certa.mp3',
    description: 'Programe seu relógio biológico para acordar disposto e pronto antes da abertura do mercado.',
  },
  {
    id: 'track-ah-esdaile',
    title: 'Chegando no Estado de Esdaile',
    subtitle: 'Transe Hipnótico Profundo',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 900,
    formattedDuration: '15:00',
    sourceUri: 'AH-chegando.no.estado.de.esdaile.mp3',
    description: 'Alcance o estado mais profundo de relaxamento e anestesia física para regeneração completa.',
  },
  {
    id: 'track-ah-melhor-versao',
    title: 'Autoterapia: Ativando a Sua Melhor Versão',
    subtitle: 'Integração de Recursos Interiores',
    author: 'Guilherme Cardoso',
    category: 'auto_hypnosis',
    durationSeconds: 880,
    formattedDuration: '14:40',
    sourceUri: 'autoterapia.ativando.a.sua.melhor.versao.mp3',
    description: 'Conecte-se com o seu arquétipo de trader experiente, consistente e inabalável.',
  },

  // 7. Consistência Emocional (Thais)
  {
    id: 'track-ce-1',
    title: '01. Privação Emocional',
    subtitle: 'Consistência Emocional',
    author: 'Thais',
    category: 'emotional_consistency',
    durationSeconds: 530,
    formattedDuration: '08:50',
    sourceUri: 'Thais-1.Privacao.Emocional.mp3',
    description: 'Compreenda como carências emocionais e busca inconsciente por preenchimento afetam suas decisões e entradas no mercado.',
  },
  {
    id: 'track-ce-2',
    title: '02. Abandono',
    subtitle: 'Consistência Emocional',
    author: 'Thais',
    category: 'emotional_consistency',
    durationSeconds: 417,
    formattedDuration: '06:57',
    sourceUri: 'Thais-2.Abandono.mp3',
    description: 'A ferida de abandono, o medo de ficar de fora dos movimentos (FOMO) e a busca ansiosa por validação nos trades.',
  },
  {
    id: 'track-ce-3',
    title: '03. Desconfiança',
    subtitle: 'Consistência Emocional',
    author: 'Thais',
    category: 'emotional_consistency',
    durationSeconds: 780,
    formattedDuration: '13:00',
    sourceUri: 'Thais-3.Desconfianca.mp3',
    description: 'Superando a desconfiança no seu método, nas leituras de fluxo/gráfico e na sua própria capacidade de execução precisa.',
  },
  {
    id: 'track-ce-4',
    title: '04. Isolamento',
    subtitle: 'Consistência Emocional',
    author: 'Thais',
    category: 'emotional_consistency',
    durationSeconds: 474,
    formattedDuration: '07:54',
    sourceUri: 'Thais-4.Isolamento.mp3',
    description: 'A solidão da tela de operações, a sensação de incompreensão e como sustentar a autonomia sem adoecer mentalmente.',
  },
  {
    id: 'track-ce-5',
    title: '05. Vergonha',
    subtitle: 'Consistência Emocional',
    author: 'Thais',
    category: 'emotional_consistency',
    durationSeconds: 612,
    formattedDuration: '10:12',
    sourceUri: 'Thais-5.Vergonha.mp3',
    description: 'Ressignificando a dor do erro e do stop loss, libertando sua mente do peso do julgamento próprio e de terceiros.',
  },
  {
    id: 'track-ce-6',
    title: '06. Fracasso',
    subtitle: 'Consistência Emocional',
    author: 'Thais',
    category: 'emotional_consistency',
    durationSeconds: 800,
    formattedDuration: '13:20',
    sourceUri: 'Thais-6.Fracasso.mp3',
    description: 'Desarmando o esquema de fracasso: o loss como custo operacional e métrica probabilística, nunca como identidade pessoal.',
  },
  {
    id: 'track-ce-7',
    title: 'O Luto Invisível do Trader',
    subtitle: 'Consistência Emocional',
    author: 'Thais',
    category: 'emotional_consistency',
    durationSeconds: 851,
    formattedDuration: '14:11',
    sourceUri: 'Thais-O.Luto.Invisivel.do.Trader.mp3',
    description: 'O processo silencioso de luto por tempo, expectativas e capital deixados para trás, e a cura mental para renascer consistente.',
  },
];

export const CATEGORY_LABELS: Record<AudioCategory, { title: string; subtitle: string; icon: string }> = {
  pre_market: {
    title: 'Preparação Matinal & Blindagem',
    subtitle: 'Afirmações de identidade vencedora e paciência pré-pregão',
    icon: 'sunrise',
  },
  binaural_focus: {
    title: 'Frequências Foco & Binaural Beats',
    subtitle: 'Ondas Alfa, Teta e Gama para concentração cirúrgica',
    icon: 'headphones',
  },
  post_loss: {
    title: 'Recuperação Pós-Loss & Anti-Tilt',
    subtitle: 'Reprogramação imediata para travar o cérebro no stop',
    icon: 'shield-alert',
  },
  decompression: {
    title: 'Descompressão & Sono Reparador',
    subtitle: 'Desligando o mercado da mente e meditação profunda',
    icon: 'moon',
  },
  trading_zone_book: {
    title: 'Audiolivro: Trading in the Zone',
    subtitle: 'Obra prima de Mark Douglas completa em 12 capítulos',
    icon: 'book-open',
  },
  auto_hypnosis: {
    title: 'Auto-Hipnose & Reprogramação',
    subtitle: 'Sessões de transe para reprogramação subconsciente de alta performance',
    icon: 'sparkles',
  },
  emotional_consistency: {
    title: 'Consistência Emocional',
    subtitle: 'Esquemas emocionais, autoimagem e superação do luto no mercado',
    icon: 'brain',
  },
};
