import { AudioCategory, AudioTrack } from '../types';

export const AUDIO_CATALOG: AudioTrack[] = [
  // 1. Preparação Matinal & Blindagem Mental
  {
    id: 'track-pre-1',
    title: 'O STOP Não é o Problema',
    subtitle: 'Reprogramação de Identidade Vencedora',
    author: 'Trading Mindset',
    category: 'pre_market',
    durationSeconds: 184,
    formattedDuration: '03:04',
    sourceUri: '/audios/Identidade/O STOP não é o problema(IA).mp3',
    description: 'Compreenda a natureza do stop loss como ferramenta de proteção patrimonial, e não como falha pessoal.',
  },
  {
    id: 'track-pre-2',
    title: 'Eu Sou um Executor de Probabilidades',
    subtitle: 'Blindagem Emocional Pré-Abertura',
    author: 'Mark Douglas Inspired',
    category: 'pre_market',
    durationSeconds: 320,
    formattedDuration: '05:20',
    sourceUri: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=meditation-mindfulness-ambient-112191.mp3',
    description: 'Ancoragem mental para enxergar o mercado sem expectativas irreais e com total disciplina de execução.',
  },
  {
    id: 'track-pre-3',
    title: 'Paciência de Franco-Atirador',
    subtitle: 'Controle de FOMO e Impulsividade',
    author: 'Trading Mindset',
    category: 'pre_market',
    durationSeconds: 275,
    formattedDuration: '04:35',
    sourceUri: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=ambient-piano-amp-strings-10711.mp3',
    description: 'Aprenda a esperar sentado o candle perfeito se formar sem ansiedade.',
  },

  // 2. Frequências Foco & Binaural Beats
  {
    id: 'binaural-alpha-10hz',
    title: 'Ondas Alfa (10 Hz) — Flow State Sniper',
    subtitle: 'Foco Profundo e Calma Operacional',
    author: 'Frequência Binaural Pura',
    category: 'binaural_focus',
    durationSeconds: 1800,
    formattedDuration: '30:00',
    sourceUri: 'binaural:alpha:10',
    isBinauralGen: true,
    binauralFreq: 10,
    description: 'Frequência alfa de 10Hz para induzir o estado de fluxo mental (flow), desacelerando a mente sem causar sonolência.',
  },
  {
    id: 'binaural-theta-6hz',
    title: 'Ondas Teta (6 Hz) — Redução de Ansiedade',
    subtitle: 'Estabilidade Emocional no Pregão',
    author: 'Frequência Binaural Pura',
    category: 'binaural_focus',
    durationSeconds: 1800,
    formattedDuration: '30:00',
    sourceUri: 'binaural:theta:6',
    isBinauralGen: true,
    binauralFreq: 6,
    description: 'Frequência teta de 6Hz ideal para momentos de alta tensão no mercado e volatilidade extrema.',
  },
  {
    id: 'binaural-gamma-40hz',
    title: 'Ondas Gama (40 Hz) — Hiperfoco e Precisão',
    subtitle: 'Processamento Visual e Decisão Rápida',
    author: 'Frequência Binaural Pura',
    category: 'binaural_focus',
    durationSeconds: 1800,
    formattedDuration: '30:00',
    sourceUri: 'binaural:gamma:40',
    isBinauralGen: true,
    binauralFreq: 40,
    description: 'Estimulação de ondas gama para máxima atenção aos padrões de candles e microestrutura do book.',
  },
  {
    id: 'track-binaural-ambient',
    title: 'Lo-Fi Zen — Operando em Silêncio',
    subtitle: 'Música Ambiente sem Distração',
    author: 'Trading Sanctuary',
    category: 'binaural_focus',
    durationSeconds: 600,
    formattedDuration: '10:00',
    sourceUri: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=lofi-study-112191.mp3',
    description: 'Batidas suaves e constantes para abafar ruídos externos durante a sessão de operações.',
  },

  // 3. Recuperação Pós-Loss & Anti-Tilt
  {
    id: 'track-loss-1',
    title: 'Você Decide Quando Quebrar',
    subtitle: 'Neurociência para Travar o Cérebro no Loss',
    author: 'Thamara & Neurociência',
    category: 'post_loss',
    durationSeconds: 520,
    formattedDuration: '08:40',
    sourceUri: '/audios/Insights/Thamara - Você decide quando QUEBRAR - NEUROCIÊNCIA para travar o seu CÉREBRO no Loss.mp3',
    description: 'Entenda os mecanismos químicos do cérebro no momento da dor da perda e como abortar a espiral do tilt.',
  },
  {
    id: 'track-loss-2',
    title: 'Dica Infalível para Melhorar Resultados',
    subtitle: 'Controle Comportamental Imediato',
    author: 'Insights de Trading',
    category: 'post_loss',
    durationSeconds: 425,
    formattedDuration: '07:05',
    sourceUri: '/audios/Insights/Siga esta DICA INFALÍVEL e seus Resultados vão mel.mp3',
    description: 'O ajuste fino entre técnica e disciplina que transforma consistência em realidade.',
  },
  {
    id: 'track-loss-3',
    title: 'O Loss é Apenas o Custo do Negócio',
    subtitle: 'Desarmando o Sentimento de Vingança',
    author: 'Trading Mindset Coach',
    category: 'post_loss',
    durationSeconds: 190,
    formattedDuration: '03:10',
    sourceUri: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=meditation-bell-112191.mp3',
    description: 'Reprograme o loss como uma despesa operacional normal de qualquer empresa lucrativa.',
  },

  // 4. Descompressão Pós-Mercado & Sono Reparador
  {
    id: 'track-decomp-1',
    title: 'Meditação Guiada para Traders',
    subtitle: 'Descompressão e Equilíbrio Mental',
    author: 'Luana Schneider',
    category: 'decompression',
    durationSeconds: 585,
    formattedDuration: '09:45',
    sourceUri: '/audios/Meditations/Meditação Guiada para Traders [Luana Schneider].mp3',
    description: 'Meditação focada em desacelerar os batimentos cardíacos e liberar a tensão muscular acumulada no pregão.',
  },
  {
    id: 'track-decomp-2',
    title: 'Meditação Profunda para Traders',
    subtitle: 'Equilíbrio e Clareza Mental',
    author: 'Guilherme Cardoso',
    category: 'decompression',
    durationSeconds: 1074,
    formattedDuration: '17:54',
    sourceUri: '/audios/Meditations/Meditação Para Traders [Guilherme Cardoso].mp3',
    description: 'Sessão completa de visualização mental e recondicionamento subconsciente para consistência.',
  },
  {
    id: 'track-decomp-3',
    title: 'Desligando o Mercado da Mente',
    subtitle: 'Higiene do Sono do Trader de Futuros',
    author: 'Mindset Sanctuary',
    category: 'decompression',
    durationSeconds: 480,
    formattedDuration: '08:00',
    sourceUri: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_c9769da891.mp3?filename=deep-sleep-ambient-112191.mp3',
    description: 'Feche as cotações mentalmente e prepare um sono reparador para o próximo dia.',
  },

  // 5. Audiolivro Trading in the Zone (Mark Douglas)
  {
    id: 'track-tiz-1',
    title: '01. O Caminho para o Sucesso',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 968,
    formattedDuration: '16:08',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/01. O Caminho para o Sucesso.mp3',
    description: 'A análise fundamentalista, técnica e a evolução para a análise mental no mercado.',
  },
  {
    id: 'track-tiz-2',
    title: '02. O Fascínio e os Perigos do Trading',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1017,
    formattedDuration: '16:57',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/02. O fascinio e os perigos do trading.mp3',
    description: 'A atração pela liberdade e a necessidade de criar regras internas estritas.',
  },
  {
    id: 'track-tiz-3',
    title: '03. Assumir Responsabilidade',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1935,
    formattedDuration: '32:15',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/03. Assumir responsabilidade.mp3',
    description: 'Moldar seu ambiente mental e assumir a responsabilidade total de cada clique.',
  },
  {
    id: 'track-tiz-4',
    title: '04. Consistência: Um Estado Mental',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 895,
    formattedDuration: '14:55',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/04. Consistencia - um estado mental.mp3',
    description: 'Entendendo o risco e o alinhamento de crenças para não hesitar.',
  },
  {
    id: 'track-tiz-5',
    title: '05. A Dinâmica da Percepção',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1570,
    formattedDuration: '26:10',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/05. A dinamica da percepcao.mp3',
    description: 'Depurando seu software mental e a relação entre medo e distorção da realidade.',
  },
  {
    id: 'track-tiz-6',
    title: '06. A Perspectiva do Mercado',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 2000,
    formattedDuration: '33:20',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/06. A perspectiva do mercado.mp3',
    description: 'O princípio da incerteza e a característica mais fundamental do mercado.',
  },
  {
    id: 'track-tiz-7',
    title: '07. A Essência do Trader',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 3683,
    formattedDuration: '1:01:23',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/07. A essencia do trader.mp3',
    description: 'Pensar em termos de probabilidades e o modelo dos cassinos.',
  },
  {
    id: 'track-tiz-8',
    title: '08. Trabalhar com Suas Convicções',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1550,
    formattedDuration: '25:50',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/08. Trabalhar com suas convicções.mp3',
    description: 'Definir o problema e gerenciar crenças conflitantes.',
  },
  {
    id: 'track-tiz-9',
    title: '09. A Natureza das Convicções',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1820,
    formattedDuration: '30:20',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/09. A natureza das conviccoes.mp3',
    description: 'As origens de uma convicção e como ela impacta nossa vida.',
  },
  {
    id: 'track-tiz-10',
    title: '10. O Impacto das Convicções no Trading',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 2925,
    formattedDuration: '48:45',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/10. O impacto das conviccoes.mp3',
    description: 'A autoavaliação primária e a eliminação do medo de errar.',
  },
  {
    id: 'track-tiz-11',
    title: '11. Pensar Como um Trader',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 2550,
    formattedDuration: '42:30',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/11. Pensar como um trader.mp3',
    description: 'O estágio mecânico, a regra do stop loss e a aceitação do risco.',
  },
  {
    id: 'track-tiz-12',
    title: '12. Aprenda com os Cassinos',
    subtitle: 'Trading in the Zone',
    author: 'Mark Douglas',
    category: 'trading_zone_book',
    durationSeconds: 1840,
    formattedDuration: '30:40',
    sourceUri: '/audios/Trading-in-the-Zone_Mark Douglas/12. Aprenda com os cassinos.mp3',
    description: 'Como uma vantagem matemática de 55% gera consistência milionária a longo prazo.',
  },
];

export const CATEGORY_LABELS: Record<AudioCategory, { title: string; subtitle: string; icon: string }> = {
  pre_market: {
    title: 'Preparação Matinal & Blindagem',
    subtitle: 'Afirmações de identidade vencedora e paciência pré-pregão',
    icon: 'sunrise',
  },
  binaural_focus: {
    title: 'Frequências Foco & Binaural Beats',
    subtitle: 'Ondas Alfa, Teta e Gama para concentração cirúrgica',
    icon: 'headphones',
  },
  post_loss: {
    title: 'Recuperação Pós-Loss & Anti-Tilt',
    subtitle: 'Reprogramação imediata para travar o cérebro no stop',
    icon: 'shield-alert',
  },
  decompression: {
    title: 'Descompressão & Sono Reparador',
    subtitle: 'Desligando o mercado da mente e meditação profunda',
    icon: 'moon',
  },
  trading_zone_book: {
    title: 'Audiolivro: Trading in the Zone',
    subtitle: 'Obra prima de Mark Douglas completa em 12 capítulos',
    icon: 'book-open',
  },
};
